"use client";

import { useMemo } from "react";
import ViewShell, { SimulatedBadge } from "./ViewShell";

const REGIONS = [
  "North America",
  "South America",
  "Europe",
  "Africa",
  "Middle East",
  "Asia",
  "Oceania",
];

const BUCKETS = 12; // 5-minute buckets over the last hour

/** Same deterministic field used by the globe, sampled per region/time. */
function cellValue(regionIdx: number, bucketIdx: number, seed: number): number {
  const v =
    Math.sin(regionIdx * 1.7 + bucketIdx * 0.55 + seed) * 0.5 +
    Math.sin(regionIdx * 3.1 - bucketIdx * 0.9 + seed * 0.7) * 0.3 +
    Math.sin((regionIdx + bucketIdx) * 1.3) * 0.2;
  return Math.min(1, Math.max(0, 0.5 + v * 0.55));
}

/** Rose → yellow → green, matching the validated sentiment ramp. */
function cellColor(t: number): string {
  const lerp = (a: number[], b: number[], k: number) =>
    a.map((v, i) => Math.round(v + (b[i] - v) * k));
  const red = [244, 63, 94];
  const yellow = [234, 179, 8];
  const green = [74, 222, 128];
  const rgb =
    t < 0.5 ? lerp(red, yellow, t * 2) : lerp(yellow, green, (t - 0.5) * 2);
  return `rgba(${rgb[0]},${rgb[1]},${rgb[2]},${0.25 + t * 0.55})`;
}

/**
 * Regional sentiment heat grid — SIMULATED demo data (same placeholder
 * engine as the sentiment panel), refreshed per 5-minute bucket.
 */
export default function HeatmapView() {
  const seed = useMemo(
    () => Math.floor(Date.now() / (5 * 60 * 1000)) % 97,
    [],
  );

  return (
    <ViewShell
      title="SENTIMENT HEATMAP"
      subtitle="Regional mood across the last hour"
      badge={<SimulatedBadge />}
    >
      <div className="p-6">
        <div className="well overflow-x-auto rounded-xl p-5">
          <div className="min-w-[640px]">
            {/* Time axis */}
            <div className="mb-2 grid grid-cols-[140px_repeat(12,1fr)] gap-1 text-[9.5px] text-ink-faint">
              <span />
              {Array.from({ length: BUCKETS }).map((_, i) => (
                <span key={i} className="text-center tabular-nums">
                  {i === BUCKETS - 1 ? "Now" : `-${(BUCKETS - 1 - i) * 5}m`}
                </span>
              ))}
            </div>
            {REGIONS.map((region, r) => (
              <div
                key={region}
                className="grid grid-cols-[140px_repeat(12,1fr)] items-center gap-1 py-0.5"
              >
                <span className="pr-3 text-[11.5px] font-medium text-ink-dim">
                  {region}
                </span>
                {Array.from({ length: BUCKETS }).map((_, b) => {
                  const v = cellValue(r, b, seed);
                  return (
                    <div
                      key={b}
                      title={`${region} · ${b === BUCKETS - 1 ? "now" : `${(BUCKETS - 1 - b) * 5}m ago`} · ${Math.round(v * 100)}% positive (simulated)`}
                      className="h-8 rounded-[5px] transition-transform hover:scale-105"
                      style={{ background: cellColor(v) }}
                    />
                  );
                })}
              </div>
            ))}

            {/* Scale */}
            <div className="mt-4 flex items-center gap-3">
              <span className="text-[10px] text-ink-faint">Very negative</span>
              <div
                className="h-1.5 w-40 rounded-full"
                style={{
                  background:
                    "linear-gradient(90deg, #f43f5e, #eab308, #4ade80)",
                }}
              />
              <span className="text-[10px] text-ink-faint">Very positive</span>
            </div>
          </div>
        </div>

        <p className="mt-4 text-[11.5px] leading-relaxed text-ink-faint">
          This heatmap is generated by the internal placeholder sentiment
          engine — it is not real social data. Connecting a social listening
          API replaces it with live regional sentiment.
        </p>
      </div>
    </ViewShell>
  );
}
